import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { GetBikes } from '../api-client/endpoints/bikes'

const Home: NextPage = () => {

  const [data, setData] = useState('')


  const handleClick = async () => {
    const res = await GetBikes()
    setData(JSON.stringify(res))
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={handleClick}>Fetch Bikes</button>
      {data ? <p>{data}</p> : ""}

    </div>
  )
}

export default Home
