import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import React from 'react';
import List from './components/list';
Table
import { GetBikes } from '../api-client/endpoints/bikes'
import Table from './components/table';
import { useBikeData } from './context/context';


const Home: NextPage = () => {

  const { bikeData, setBikeData } = useBikeData()

  const handleClick = async () => {
    const res = await GetBikes()
    setBikeData(res.data.nb.feeds)

    // setData(JSON.stringify(response))
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex justify-center'>
        <div className='text-center'>
          <button className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' onClick={handleClick}>Fetch Bikes</button>
          {bikeData ? <Table data={bikeData} /> : "" }
        </div>
      </div>
    </div>
  )
}

export default Home
